# Generated by Django 5.2.3 on 2025-07-13 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologies', '0002_alter_technology_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('technologies', models.ManyToManyField(blank=True, related_name='profiles', to='technologies.technology')),
            ],
        ),
        migrations.CreateModel(
            name='CareerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('education', 'Education'), ('experience', 'Experience')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, default='Independent', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_items', to='profiles.professionalprofile')),
            ],
        ),
    ]
