# Generated by Django 5.2.3 on 2025-07-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeritem',
            name='institution',
            field=models.CharField(blank=True, default='Independiente', max_length=200, null=True),
        ),
    ]
