# Generated by Django 5.2.3 on 2025-07-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='technologies.technology'),
        ),
    ]
