# Generated by Django 5.2.3 on 2025-07-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['name'], 'verbose_name_plural': 'Technologies'},
        ),
    ]
